import { Loading } from "@mui-verse/ui/components/effects";
import { fontVariables, ThemeProvider } from "@mui-verse/ui/theme";
import type { Metadata } from "next";
import { Suspense } from "react";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={fontVariables} suppressHydrationWarning>
      <body>
        <ThemeProvider>
          <div className="flex h-screen w-full">
            <Suspense fallback={<Loading />}>
              {children}
            </Suspense>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
