import { ThemeProvider } from "@mui-verse/ui/theme/ThemeProvider";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`h-full antialiased`}>
      <body>
        <ThemeProvider>
          <div className="w-full">{children}</div>
        </ThemeProvider>
      </body>
    </html>
  );
}
